"""add delivery, bucket, queue

Revision ID: 27ffd8373bc4
Revises: 2070e99383ed
Create Date: 2016-02-20 11:45:15.732956

"""

# revision identifiers, used by Alembic.
revision = '27ffd8373bc4'
down_revision = '2070e99383ed'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_empty', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bucket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('schedule', sa.Integer(), nullable=True),
    sa.Column('max_item', sa.Integer(), nullable=True),
    sa.Column('queue', sa.Integer(), nullable=True),
    sa.Column('delivery_method', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_method'], ['delivery.id'], ),
    sa.ForeignKeyConstraint(['owner'], ['user.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['queue'], ['queue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bucket')
    op.drop_table('queue')
    ### end Alembic commands ###
