"""added the rest of the tables, along with helpers

Revision ID: 880220fbd9f2
Revises: 27ffd8373bc4
Create Date: 2016-02-20 12:13:31.824588

"""

# revision identifiers, used by Alembic.
revision = '880220fbd9f2'
down_revision = '27ffd8373bc4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('last_polled', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('date_polled', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source'], ['source.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_tags',
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='cascade')
    )
    op.create_table('source_type_RSS',
    sa.Column('source', sa.Integer(), nullable=False),
    sa.Column('format', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['source'], ['source.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('source')
    )
    op.create_table('source_type__reminder',
    sa.Column('source', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['source'], ['source.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('source')
    )
    op.create_table('queue_contents',
    sa.Column('queue_id', sa.Integer(), nullable=True),
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['queue_id'], ['user.id'], ondelete='cascade')
    )
    op.create_table('bucket_sources',
    sa.Column('bucket.id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bucket.id'], ['bucket.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ondelete='cascade')
    )
    op.create_table('source_type__bucket',
    sa.Column('source', sa.Integer(), nullable=False),
    sa.Column('bucket', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bucket'], ['bucket.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['source'], ['source.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('source')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('source_type__bucket')
    op.drop_table('bucket_sources')
    op.drop_table('queue_contents')
    op.drop_table('source_type__reminder')
    op.drop_table('source_type_RSS')
    op.drop_table('source_tags')
    op.drop_table('content')
    op.drop_table('tag')
    op.drop_table('source_type')
    op.drop_table('source')
    ### end Alembic commands ###
